### ISSUE TITLE
No validation of Country Code.

### ISSUE THREAD

**Issue by thatfreakcoder** [iamyajat/WhatsAppThem#1]
Whatsapp Dynamic Link (wa.me) requires a country code in the beginning. Currently, no such validation is preventing it from redirecting.

**Comment by cryptus-neoxys** [comment]
Is this up for grabs?

**Comment by iamyajat** [comment]
Sure go ahead @cryptus-neoxys

**Comment by cryptus-neoxys** [comment]
What would be the best approach for this?
- IP address lookup to get user's location (probably overkill)
- GeoLocation API? (poor UX, possibly)

**Comment by iamyajat** [comment]
If I'm not wrong, for geolocation, the user will have to grant location access which I think will harm the simplicity of the app.

Maybe this can be used to get the country.
```js
$.get("http://ipinfo.io", function(response) {
    console.log(response.city, response.country);
}, "jsonp");
```

One more thing, if the user pastes the number directly with a country code then, modify the selected country automatically.

**Comment by cryptus-neoxys** [comment]
Yeah, similar issues regarding geolocation API requesting permission.

Here's what I could think of as a better alternative: Use [geolocation-db](https://geolocation-db.com/documentation)'s ultimate free service to get the Country data and map that to country Phone code [Country Code to Phone Code-JSON](https://pastebin.com/UQ2CXkHZ)
This can then be cached on the user's device for a seamless exp (PWA and whatnot xD)

**Comment by iamyajat** [comment]
Looks good!

**Comment by cryptus-neoxys** [comment]
Self-hosted alternative:

https://lite.ip2location.com/ip2location-lite
