### ISSUE TITLE
Add bulk message option

### ISSUE THREAD

**Issue by iamyajat** [iamyajat/WhatsAppThem#3]
Allow sending messages in bulk.

**Comment by cryptus-neoxys** [comment]
Does WhatsApp's messaging via URL allow for bulk messages?

**Comment by iamyajat** [comment]
Maybe not, but I haven't done much research on it... So I'm not sure.

**Comment by iamyajat** [comment]
As of now, there doesn't seem to be any solution for this issue using the URL. Therefore, I am closing this issue.
