### ISSUE TITLE
Add phone number parsing and validation

### ISSUE THREAD

**Issue by cryptus-neoxys** [iamyajat/WhatsAppThem#5]
Currently the simply input takes in any text input from the user and redirects them to a possibly invalid URL.

The ```type=tel``` attribute doesn't really work here as the input field can't be validated without a form submission, as there is NO FORM!

Here's a few suggestion, that can be built on:

- [x] #6
- [x] #7
- [x] Display error/warn message (preferably on input change)

**Comment by surbhit14** [comment]
I would like to work on this issue

**Comment by iamyajat** [comment]
Sure @surbhit14

**Comment by iamyajat** [comment]
Are you still working on this issue @surbhit14?

**Comment by surbhit14** [comment]
I am sorry.
Due to some other prior commitments I won't be able to work on this issue
now

Sorry for the inconvenience.

**Comment by iamyajat** [comment]
no problem @surbhit14, have a great day!
